version: '3'
volumes:
    grafana-storage:
    prometheus-storage:
    alertmanager-storage:
services: 
    prometheus:
        image: prom/prometheus
        command: ["--config.file=/prometheus-data/prometheus.yml"]
        volumes: 
            - ./prometheus-data:/prometheus-data
            - prometheus-storage:/prometheus
        ports:
            - 9090:9090
    grafana:
        image: grafana/grafana
        volumes:
            - grafana-storage:/var/lib/grafana
        ports:
            - 3000:3000
        environment:
            - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource       
        depends_on: 
            - prometheus
    alertmanager:
        image: prom/alertmanager
        command: ["--config.file=/alertmanager/alertmanager.yaml"]
        volumes:
            - ./alertmanager:/alertmanager
            - alertmanager-storage:/alertmanager/data
        ports:
            - 9093:9093
        environment:
            PAGERDUTY_EMAIL: ${PAGERDUTY_EMAIL}
            PAGERDUTY_KEY: ${PAGERDUTY_KEY}WW