{
 "title": "OPEN ALERTS",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "TOTAL ALERTS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "OPEN ALERTS",
   "type": "table",
   "gridPos": { "h": 16, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}",
     "legendFormat": "{{msg}}"
    }
   ]
  },
  {
   "title": "SERVICE DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertname=\"service_down\",alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "TOTAL CRITICAL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity='critical',alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "TOTAL WARNING",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{severity='warning',alertstate=\"firing\"})"
    }
   ]
  },
  {
   "title": "ALERT BY NAME",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (alertname)",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "ALERTS IN TIME",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"})",
     "legendFormat": "{{alertname}}"
    }
   ]
  },
  {
   "title": "ALERT BY SEVERITY",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (severity)",
     "legendFormat": "{{severity}}"
    }
   ]
  }
 ]
}